spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}
---
spring:
  profiles: local-h2
  datasource:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  datasource:
      url: jdbc:mysql://192.168.9.196:32001/testdb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver